---
- name: Ensure os is up to date
  ansible.builtin.apt:
    update_cache: true
    upgrade: true


- name: Ensure kernal is up to date
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    autoclean: true
  notify:
    - Reboot required

- name: Ensure old patches are removed
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
  notify:
    - Reboot required
